### PR TITLE
Fix some unit using International System notaion for powers

### PR DESCRIPTION
**Pull request by mathieupotier**
https://github.com/sermatec-opensource/homeassistant-sermatec-inverter/issues/50

### CODE REVIEW

**Comment by andreondra** [comment]
Thanks 😁

I'll copy it to the HA repo after [this](https://github.com/sermatec-opensource/homeassistant-sermatec-inverter/pull/49) is resolved, so there are no conflicts. When you have time, please have a look at it :).

**Comment by mathieupotier** [comment]
just updated my homeassistant instance with this PR ...
I'll monitor log for a couple of hours ...

**Comment by mathieupotier** [comment]
Got this few times, but seems not crashing the integration anymore ...
```
2024-04-17 17:32:34.466 DEBUG (MainThread) [custom_components.sermatec_inverter.sermatec_inverter.protocol_parser] Built command: ['0xfe', '0x55', '0x64', '0x14', '0xd', '0x0', '0x0', '0xd9', '0xae']
2024-04-17 17:32:34.466 DEBUG (MainThread) [custom_components.sermatec_inverter.sermatec_inverter] Communicating with inverter, command 0d, attempt 1/5
2024-04-17 17:32:34.621 DEBUG (MainThread) [custom_components.sermatec_inverter.sermatec_inverter] Received data: fe 55 14 64 a2 00 44 ff fd 00 5f 00 02 00 0f 01 0e 00 00 05 64 05 9b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 14 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 07 e7 01 0c 16 1a 34 02 51 ae
2024-04-17 17:32:34.621 DEBUG (MainThread) [custom_components.sermatec_inverter.sermatec_inverter.protocol_parser] Bad response expected command. Expected: 0d, got: a2.
2024-04-17 17:32:34.621 DEBUG (MainThread) [custom_components.sermatec_inverter.sermatec_inverter] Command 0x0d data malformed.
2024-04-17 17:32:34.621 DEBUG (MainThread) [custom_components.sermatec_inverter.sermatec_inverter] Communicating with inverter, command 0d, attempt 2/5
2024-04-17 17:32:34.797 DEBUG (MainThread) [custom_components.sermatec_inverter.sermatec_inverter] Received data: fe 55 14 64 bb 00 22 00 08 40 88 14 e4 40 89 14 1e 40 8a 12 8e 40 8b 11 fa 40 8c 00 02 40 8d 00 06 40 8e 00 06 40 8f 00 02 c8 ae
2024-04-17 17:32:34.797 DEBUG (MainThread) [custom_components.sermatec_inverter.sermatec_inverter.protocol_parser] Bad response expected command. Expected: 0d, got: bb.
2024-04-17 17:32:34.798 DEBUG (MainThread) [custom_components.sermatec_inverter.sermatec_inverter] Command 0x0d data malformed.
2024-04-17 17:32:34.798 DEBUG (MainThread) [custom_components.sermatec_inverter.sermatec_inverter] Communicating with inverter, command 0d, attempt 3/5
2024-04-17 17:32:35.031 DEBUG (MainThread) [custom_components.sermatec_inverter.sermatec_inverter] Received data: fe 55 14 64 95 00 94 00 00 00 00 00 00 00 00 13 88 00 00 00 01 00 00 00 03 00 ee 00 00 00 14 00 01 00 00 05 9f 00 03 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 06 00 01 00 00 00 1e 00 03 34 ae
2024-04-17 17:32:35.031 DEBUG (MainThread) [custom_components.sermatec_inverter.sermatec_inverter.protocol_parser] Bad response expected command. Expected: 0d, got: 95.
2024-04-17 17:32:35.032 DEBUG (MainThread) [custom_components.sermatec_inverter.sermatec_inverter] Command 0x0d data malformed.
2024-04-17 17:32:35.032 DEBUG (MainThread) [custom_components.sermatec_inverter.sermatec_inverter] Communicating with inverter, command 0d, attempt 4/5
2024-04-17 17:32:35.197 DEBUG (MainThread) [custom_components.sermatec_inverter.sermatec_inverter] Received data: fe 55 14 64 9d 00 2e 00 ee ee 00 00 0a 00 01 00 0c 00 00 00 00 ee 00 10 68 13 88 00 00 02 58 01 90 00 00 00 ee 00 05 00 05 00 01 00 c8 00 01 00 00 00 00 00 ff 7f ae
2024-04-17 17:32:35.197 DEBUG (MainThread) [custom_components.sermatec_inverter.sermatec_inverter.protocol_parser] Bad response expected command. Expected: 0d, got: 9d.
2024-04-17 17:32:35.197 DEBUG (MainThread) [custom_components.sermatec_inverter.sermatec_inverter] Command 0x0d data malformed.
2024-04-17 17:32:35.198 DEBUG (MainThread) [custom_components.sermatec_inverter.sermatec_inverter] Communicating with inverter, command 0d, attempt 5/5
2024-04-17 17:32:35.407 DEBUG (MainThread) [custom_components.sermatec_inverter.sermatec_inverter] Received data: fe 55 14 64 a2 00 44 ff fd 00 5f 00 02 00 0f 01 0e 00 00 05 64 05 9b 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 14 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 07 e7 01 0c 16 1a 34 02 51 ae
2024-04-17 17:32:35.407 DEBUG (MainThread) [custom_components.sermatec_inverter.sermatec_inverter.protocol_parser] Bad response expected command. Expected: 0d, got: a2.
2024-04-17 17:32:35.407 DEBUG (MainThread) [custom_components.sermatec_inverter.sermatec_inverter] Command 0x0d data malformed.
2024-04-17 17:32:35.407 ERROR (MainThread) [custom_components.sermatec_inverter.sermatec_inverter] Unable to receive correct response after 5 tries.
```

**Comment by andreondra** [comment]
Hi, can you please change "VAr" to lowercase "var"? See [metric directive](https://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=OJ:L:1980:039:0040:0050:EN:PDF#page=6) and also [Home Assistant docs](https://developers.home-assistant.io/docs/core/entity/sensor#available-device-classes).

**Comment by mathieupotier** [comment]
All done 😁

**Pull request merged**
